const contacts = [
    {
        "id": 1,
        "hero_name": "Iron Man",
        "name": "Tony Stark",
        "email": "iron.man@mavel.com",
        "phone": "0123456789",
        "dob": "1970-05-29",
        "address": "Unknow",
        "avatar": "https://mcdn.coolmate.me/image/August2022/3I1dQwRwU0TuUOqLV3Aa_931.jpg",
        "detail": "Inventor Tony Stark applies his genius for high-tech solutions to problems as Iron Man, the armored Avenger.",
        "gender": "male"
    },
    {
        "id": 2,
        "hero_name": "Captain America",
        "name": "Steve Rogers",
        "email": "captain.america@mavel.com",
        "phone": "0392847568",
        "dob": "1920-07-04",
        "address": "Unknow",
        "avatar": "https://mcdn.coolmate.me/image/August2022/uaSTz6c2hxDyuBjMIZ32_261.jpg",
        "detail": "America’s World War II Super-Soldier continues his fight in the present as an Avenger and untiring sentinel of liberty.",
        "gender": "male"
    },
    {
        "id": 3,
        "hero_name": "Spider Man",
        "name": "Peter Parker",
        "email": "spider.man@mavel.com",
        "phone": "0736187384",
        "dob": "1962-10-10",
        "address": "Unknow",
        "avatar": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT9RM1X1LhnL8E8eMV4jJEpoOxIrgytdh2Ddw&usqp=CAU",
        "detail": "With amazing spider-like abilities, teenage science whiz Peter Parker fights crime and dreams of becoming an Avenger as Spider-Man.",
        "gender": "male"
    },
    {
        "id": 4,
        "hero_name": "Black Widow",
        "name": "Natasha Romanoff",
        "email": "black.widow@mavel.com",
        "phone": "0726485639",
        "dob": "1984-12-03",
        "address": "Unknow",
        "avatar": "https://mcdn.coolmate.me/image/August2022/J-zqlIIlS4x3eMxgPneJ_496.jpg",
        "detail": "A deadly assassin is closing in on Natasha Romanoff. Now Natasha must reunite with an unlikely group of spies from her past in order to survive and stop a lethal force from being unleashed on the world.",
        "gender": "female"
    },
    {
        "id": 5,
        "hero_name": "Scarlet Witch",
        "name": "Wanda Maximoff",
        "email": "scarlet.witch@mavel.com",
        "phone": "0383749274",
        "dob": "1989-01-01",
        "address": "Unknow",
        "avatar": "https://marvelwikiblog.files.wordpress.com/2016/05/scarlet-witch.jpg?w=816",
        "detail": "Notably powerful, Wanda Maximoff has fought both against and with the Avengers, attempting to hone her abilities and do what she believes is right to help the world.",
        "gender": "female"
    },
    {
        "id": 6,
        "hero_name": "Thor",
        "name": "Thor Odinson",
        "email": "thor@mavel.com",
        "phone": "0827487365",
        "dob": "1989-01-01",
        "address": "Unknow",
        "avatar": "https://mcdn.coolmate.me/image/August2022/raNQUq3cm1UI0DMnoB2c_616.jpg",
        "detail": "Thor Odinson wields the power of the ancient Asgardians to fight evil throughout the Nine Realms and beyond.",
        "gender": "male"
    },
    {
        "id": 7,
        "hero_name": "Hulk",
        "name": "Bruce Banner",
        "email": "hulk@mavel.com",
        "phone": "0827461890",
        "dob": "1989-01-01",
        "address": "Unknow",
        "avatar": "https://mcdn.coolmate.me/image/August2022/MQw0Jm2G8qzfRkr1pQAK_310.jpg",
        "detail": "Notably powerful, Wanda Maximoff has fought both against and with the Avengers, attempting to hone her abilities and do what she believes is right to help the world.",
        "gender": "male"
    },
    {
        "id": 8,
        "hero_name": "Hawkeye",
        "name": "Clint Barton",
        "email": "hawkeye@mavel.com",
        "phone": "0767534578",
        "dob": "1989-01-01",
        "address": "Unknow",
        "avatar": "https://mcdn.coolmate.me/image/August2022/VVbfPiGL1DZOmO53zMuG_704.jpg",
        "detail": "An expert marksman and fighter, Clint Barton puts his talents to good use by working for S.H.I.E.L.D. as a special agent. The archer known as Hawkeye also boasts a strong moral compass that at times leads him astray from his direct orders.",
        "gender": "male"
    },
    {
        "id": 9,
        "hero_name": "Falcon",
        "name": "Sam Wilson",
        "email": "falcon@mavel.com",
        "phone": "0127654897",
        "dob": "1989-01-01",
        "address": "Unknow",
        "avatar": "https://mcdn.coolmate.me/image/August2022/OHLoKLCYx7DQjzR_adks_514.jpg",
        "detail": "When Steve Rogers asked Air Force Veteran Sam Wilson for help, Wilson immediately agreed. He donned the flight suit he’d used in combat to become the Falcon, setting him on a path towards becoming an Avenger and eventually Captain America.",
        "gender": "male"
    },
    {
        "id": 10,
        "hero_name": "Winter Soldier",
        "name": "Bucky Barnes",
        "email": "winter.soldier@mavel.com",
        "phone": "0987457532",
        "dob": "1989-01-01",
        "address": "Unknow",
        "avatar": "https://mcdn.coolmate.me/image/August2022/kBI2l-nfY1br2Ml9TFpf_630.jpg",
        "detail": "James Buchanan “Bucky” Barnes enlists to fight in World War II, but eventually literally falls in battle. Unfortunately, the evil Arnim Zola recovers him and erases his memory, turning him into a highly-trained assassin called the Winter Soldier.",
        "gender": "male"
    },
    {
        "id": 11,
        "hero_name": "War Machine",
        "name": "James Rupert",
        "email": "war.machine@mavel.com",
        "phone": "0765436865",
        "dob": "1989-01-01",
        "address": "Unknow",
        "avatar": "https://mcdn.coolmate.me/image/August2022/OZzagpl6PIlkGz9Q1gqh_330.jpg",
        "detail": "Air Force Lieutenant Colonel James “Rhodey” Rhodes exudes loyalty and courage, whether flying a plane or piloting the War Machine armor.",
        "gender": "male"
    },
    {
        "id": 12,
        "hero_name": "Ant Man",
        "name": "Scott Lang",
        "email": "ant.man@mavel.com",
        "phone": "0864786435",
        "dob": "1989-01-01",
        "address": "Unknow",
        "avatar": "https://mcdn.coolmate.me/image/August2022/REMK2rBrApe8fFJ5iWN7_583.jpg",
        "detail": "Thief turned hero Scott Lang uses size manipulation tech to infiltrate bases and intimidate bad guys. Whether he’s commanding an insect army or standing tall at 65 feet, Scott’s always trying to do the right thing now that he’s Ant-Man.",
        "gender": "male"
    },
    {
        "id": 13,
        "hero_name": "The Wasp",
        "name": "Hope Van Dyne",
        "email": "the.wasp@mavel.com",
        "phone": "0754796532",
        "dob": "1989-01-01",
        "address": "Unknow",
        "avatar": "https://mcdn.coolmate.me/image/August2022/ohxh0SU_YehII5Bi0wSE_785.jpg",
        "detail": "Daughter of the brilliant and heroic Ant-Man (Hank Pym) and The Wasp (Janet van Dyne), helps trains her father’s successor Scott Lang and secure the destruction of the Yellowjacket technology.",
        "gender": "female"
    },
    {
        "id": 14,
        "hero_name": "Star Lord",
        "name": "Peter Quill",
        "email": "star.lord@mavel.com",
        "phone": "0832736293",
        "dob": "1989-01-01",
        "address": "Unknow",
        "avatar": "https://www.gaytimes.co.uk/wp-content/uploads/2020/12/Star-Lord.jpg",
        "detail": "Would-be thief Peter Quill journeys through space as Star-Lord, the leader of the Guardians of the Galaxy.",
        "gender": "male"
    },
    {
        "id": 15,
        "hero_name": "Doctor Strange",
        "name": "Stephen Strange",
        "email": "doctor.strange@mavel.com",
        "phone": "0387228345",
        "dob": "1989-01-01",
        "address": "Unknow",
        "avatar": "https://cdnimg.vietnamplus.vn/t620/Uploaded/lepz/2016_10_28/doctorstrange.jpg",
        "detail": "Once a highly successful, yet notably egotistical, surgeon, Doctor Stephen Strange endured a terrible accident that led him to evolve in ways he could have never foreseen.",
        "gender": "male"
    },
    {
        "id": 16,
        "hero_name": "Black Panther",
        "name": "T'Challa",
        "email": "black.panther@mavel.com",
        "phone": "0933483728",
        "dob": "1989-01-01",
        "address": "Unknow",
        "avatar": "https://mcdn.coolmate.me/image/August2022/PsmRguPB34Etk3GmKZmc_295.jpg",
        "detail": "As the king of the African nation of Wakanda, T’Challa protects his people as the latest in a legacy line of Black Panther warriors.",
        "gender": "male"
    },
    {
        "id": 17,
        "hero_name": "Captain Mavel",
        "name": "Carol Danvers",
        "email": "captain.marvel@mavel.com",
        "phone": "0292846723",
        "dob": "1989-01-01",
        "address": "Unknow",
        "avatar": "https://mcdn.coolmate.me/image/August2022/53CB0msfUm69_TWsILkg_825.jpg",
        "detail": "Carol Danvers becomes one of the universe's most powerful heroes when Earth is caught in the middle of a galactic war between two alien races.",
        "gender": "female"
    },
]

export {contacts}